<?php


/**
 * This class adds structure of 'rikssym_document' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu May 27 16:34:57 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RikssymDocumentMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RikssymDocumentMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(RikssymDocumentPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(RikssymDocumentPeer::TABLE_NAME);
		$tMap->setPhpName('RikssymDocument');
		$tMap->setClassname('RikssymDocument');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('TITLE_SHORT', 'TitleShort', 'LONGVARCHAR', true, null);

		$tMap->addColumn('TITLE_LONG', 'TitleLong', 'LONGVARCHAR', false, null);

		$tMap->addColumn('TYPE', 'Type', 'VARCHAR', false, 255);

		$tMap->addColumn('DATE_SIGNED', 'DateSigned', 'INTEGER', false, null);

		$tMap->addColumn('DATE_FORCE', 'DateForce', 'INTEGER', false, null);

		$tMap->addColumn('FILENAME', 'Filename', 'VARCHAR', true, 255);

		$tMap->addColumn('LANGUAGE', 'Language', 'VARCHAR', false, 255);

	} // doBuild()

} // RikssymDocumentMapBuilder
