<?php


/**
 * This class adds structure of 'rikssym_data' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu May 27 16:34:58 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RikssymDataMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RikssymDataMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(RikssymDataPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(RikssymDataPeer::TABLE_NAME);
		$tMap->setPhpName('RikssymData');
		$tMap->setClassname('RikssymData');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addForeignKey('REPORTER_ID', 'ReporterId', 'INTEGER', 'rikssym_country', 'ID', true, null);

		$tMap->addForeignKey('PARTNER_ID', 'PartnerId', 'INTEGER', 'rikssym_country', 'ID', false, null);

		$tMap->addForeignKey('TYPE_ID', 'TypeId', 'INTEGER', 'rikssym_datatype', 'ID', true, null);

		$tMap->addColumn('VALUE', 'Value', 'BIGINT', false, null);

		$tMap->addForeignKey('SOURCE_ID', 'SourceId', 'INTEGER', 'rikssym_sources', 'ID', true, null);

		$tMap->addColumn('PERIOD', 'Period', 'INTEGER', true, null);

	} // doBuild()

} // RikssymDataMapBuilder
