<?php

/**
 * Base class that represents a row from the 'rikssym_georegion' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu May 27 16:34:57 2010
 *
 * @package    lib.model.om
 */
abstract class BaseRikssymGeoregion extends BaseObject  implements Persistent {


  const PEER = 'RikssymGeoregionPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RikssymGeoregionPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * @var        array RikssymCountry[] Collection to store aggregation of RikssymCountry objects.
	 */
	protected $collRikssymCountrys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymCountrys.
	 */
	private $lastRikssymCountryCriteria = null;

	/**
	 * @var        array RikssymArrangement[] Collection to store aggregation of RikssymArrangement objects.
	 */
	protected $collRikssymArrangements;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymArrangements.
	 */
	private $lastRikssymArrangementCriteria = null;

	/**
	 * @var        array RikssymJournal[] Collection to store aggregation of RikssymJournal objects.
	 */
	protected $collRikssymJournals;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymJournals.
	 */
	private $lastRikssymJournalCriteria = null;

	/**
	 * @var        array RikssymCenter[] Collection to store aggregation of RikssymCenter objects.
	 */
	protected $collRikssymCenters;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymCenters.
	 */
	private $lastRikssymCenterCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRikssymGeoregion object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymGeoregion The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RikssymGeoregionPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     RikssymGeoregion The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = RikssymGeoregionPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 2; // 2 = RikssymGeoregionPeer::NUM_COLUMNS - RikssymGeoregionPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RikssymGeoregion object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymGeoregionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RikssymGeoregionPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collRikssymCountrys = null;
			$this->lastRikssymCountryCriteria = null;

			$this->collRikssymArrangements = null;
			$this->lastRikssymArrangementCriteria = null;

			$this->collRikssymJournals = null;
			$this->lastRikssymJournalCriteria = null;

			$this->collRikssymCenters = null;
			$this->lastRikssymCenterCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRikssymGeoregion:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymGeoregionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RikssymGeoregionPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRikssymGeoregion:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRikssymGeoregion:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymGeoregionPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRikssymGeoregion:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RikssymGeoregionPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RikssymGeoregionPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RikssymGeoregionPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RikssymGeoregionPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collRikssymCountrys !== null) {
				foreach ($this->collRikssymCountrys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymArrangements !== null) {
				foreach ($this->collRikssymArrangements as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymJournals !== null) {
				foreach ($this->collRikssymJournals as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymCenters !== null) {
				foreach ($this->collRikssymCenters as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = RikssymGeoregionPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collRikssymCountrys !== null) {
					foreach ($this->collRikssymCountrys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymArrangements !== null) {
					foreach ($this->collRikssymArrangements as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymJournals !== null) {
					foreach ($this->collRikssymJournals as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymCenters !== null) {
					foreach ($this->collRikssymCenters as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RikssymGeoregionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RikssymGeoregionPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RikssymGeoregionPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RikssymGeoregionPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);

		if ($this->isColumnModified(RikssymGeoregionPeer::ID)) $criteria->add(RikssymGeoregionPeer::ID, $this->id);
		if ($this->isColumnModified(RikssymGeoregionPeer::NAME)) $criteria->add(RikssymGeoregionPeer::NAME, $this->name);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);

		$criteria->add(RikssymGeoregionPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RikssymGeoregion (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getRikssymCountrys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymCountry($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymArrangements() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymArrangement($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymJournals() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymJournal($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymCenters() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymCenter($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RikssymGeoregion Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RikssymGeoregionPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RikssymGeoregionPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collRikssymCountrys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymCountrys()
	 */
	public function clearRikssymCountrys()
	{
		$this->collRikssymCountrys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymCountrys collection (array).
	 *
	 * By default this just sets the collRikssymCountrys collection to an empty array (like clearcollRikssymCountrys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymCountrys()
	{
		$this->collRikssymCountrys = array();
	}

	/**
	 * Gets an array of RikssymCountry objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymGeoregion has previously been saved, it will retrieve
	 * related RikssymCountrys from storage. If this RikssymGeoregion is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymCountry[]
	 * @throws     PropelException
	 */
	public function getRikssymCountrys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymCountrys === null) {
			if ($this->isNew()) {
			   $this->collRikssymCountrys = array();
			} else {

				$criteria->add(RikssymCountryPeer::GEOREGION, $this->id);

				RikssymCountryPeer::addSelectColumns($criteria);
				$this->collRikssymCountrys = RikssymCountryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymCountryPeer::GEOREGION, $this->id);

				RikssymCountryPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymCountryCriteria) || !$this->lastRikssymCountryCriteria->equals($criteria)) {
					$this->collRikssymCountrys = RikssymCountryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymCountryCriteria = $criteria;
		return $this->collRikssymCountrys;
	}

	/**
	 * Returns the number of related RikssymCountry objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymCountry objects.
	 * @throws     PropelException
	 */
	public function countRikssymCountrys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymCountrys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymCountryPeer::GEOREGION, $this->id);

				$count = RikssymCountryPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymCountryPeer::GEOREGION, $this->id);

				if (!isset($this->lastRikssymCountryCriteria) || !$this->lastRikssymCountryCriteria->equals($criteria)) {
					$count = RikssymCountryPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymCountrys);
				}
			} else {
				$count = count($this->collRikssymCountrys);
			}
		}
		$this->lastRikssymCountryCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymCountry object to this object
	 * through the RikssymCountry foreign key attribute.
	 *
	 * @param      RikssymCountry $l RikssymCountry
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymCountry(RikssymCountry $l)
	{
		if ($this->collRikssymCountrys === null) {
			$this->initRikssymCountrys();
		}
		if (!in_array($l, $this->collRikssymCountrys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymCountrys, $l);
			$l->setRikssymGeoregion($this);
		}
	}

	/**
	 * Clears out the collRikssymArrangements collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymArrangements()
	 */
	public function clearRikssymArrangements()
	{
		$this->collRikssymArrangements = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymArrangements collection (array).
	 *
	 * By default this just sets the collRikssymArrangements collection to an empty array (like clearcollRikssymArrangements());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymArrangements()
	{
		$this->collRikssymArrangements = array();
	}

	/**
	 * Gets an array of RikssymArrangement objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymGeoregion has previously been saved, it will retrieve
	 * related RikssymArrangements from storage. If this RikssymGeoregion is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymArrangement[]
	 * @throws     PropelException
	 */
	public function getRikssymArrangements($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymArrangements === null) {
			if ($this->isNew()) {
			   $this->collRikssymArrangements = array();
			} else {

				$criteria->add(RikssymArrangementPeer::GEOREGION_ID, $this->id);

				RikssymArrangementPeer::addSelectColumns($criteria);
				$this->collRikssymArrangements = RikssymArrangementPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymArrangementPeer::GEOREGION_ID, $this->id);

				RikssymArrangementPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymArrangementCriteria) || !$this->lastRikssymArrangementCriteria->equals($criteria)) {
					$this->collRikssymArrangements = RikssymArrangementPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymArrangementCriteria = $criteria;
		return $this->collRikssymArrangements;
	}

	/**
	 * Returns the number of related RikssymArrangement objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymArrangement objects.
	 * @throws     PropelException
	 */
	public function countRikssymArrangements(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymArrangements === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymArrangementPeer::GEOREGION_ID, $this->id);

				$count = RikssymArrangementPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymArrangementPeer::GEOREGION_ID, $this->id);

				if (!isset($this->lastRikssymArrangementCriteria) || !$this->lastRikssymArrangementCriteria->equals($criteria)) {
					$count = RikssymArrangementPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymArrangements);
				}
			} else {
				$count = count($this->collRikssymArrangements);
			}
		}
		$this->lastRikssymArrangementCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymArrangement object to this object
	 * through the RikssymArrangement foreign key attribute.
	 *
	 * @param      RikssymArrangement $l RikssymArrangement
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymArrangement(RikssymArrangement $l)
	{
		if ($this->collRikssymArrangements === null) {
			$this->initRikssymArrangements();
		}
		if (!in_array($l, $this->collRikssymArrangements, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymArrangements, $l);
			$l->setRikssymGeoregion($this);
		}
	}

	/**
	 * Clears out the collRikssymJournals collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymJournals()
	 */
	public function clearRikssymJournals()
	{
		$this->collRikssymJournals = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymJournals collection (array).
	 *
	 * By default this just sets the collRikssymJournals collection to an empty array (like clearcollRikssymJournals());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymJournals()
	{
		$this->collRikssymJournals = array();
	}

	/**
	 * Gets an array of RikssymJournal objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymGeoregion has previously been saved, it will retrieve
	 * related RikssymJournals from storage. If this RikssymGeoregion is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymJournal[]
	 * @throws     PropelException
	 */
	public function getRikssymJournals($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymJournals === null) {
			if ($this->isNew()) {
			   $this->collRikssymJournals = array();
			} else {

				$criteria->add(RikssymJournalPeer::REGION_ID, $this->id);

				RikssymJournalPeer::addSelectColumns($criteria);
				$this->collRikssymJournals = RikssymJournalPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymJournalPeer::REGION_ID, $this->id);

				RikssymJournalPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymJournalCriteria) || !$this->lastRikssymJournalCriteria->equals($criteria)) {
					$this->collRikssymJournals = RikssymJournalPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymJournalCriteria = $criteria;
		return $this->collRikssymJournals;
	}

	/**
	 * Returns the number of related RikssymJournal objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymJournal objects.
	 * @throws     PropelException
	 */
	public function countRikssymJournals(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymJournals === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymJournalPeer::REGION_ID, $this->id);

				$count = RikssymJournalPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymJournalPeer::REGION_ID, $this->id);

				if (!isset($this->lastRikssymJournalCriteria) || !$this->lastRikssymJournalCriteria->equals($criteria)) {
					$count = RikssymJournalPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymJournals);
				}
			} else {
				$count = count($this->collRikssymJournals);
			}
		}
		$this->lastRikssymJournalCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymJournal object to this object
	 * through the RikssymJournal foreign key attribute.
	 *
	 * @param      RikssymJournal $l RikssymJournal
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymJournal(RikssymJournal $l)
	{
		if ($this->collRikssymJournals === null) {
			$this->initRikssymJournals();
		}
		if (!in_array($l, $this->collRikssymJournals, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymJournals, $l);
			$l->setRikssymGeoregion($this);
		}
	}

	/**
	 * Clears out the collRikssymCenters collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymCenters()
	 */
	public function clearRikssymCenters()
	{
		$this->collRikssymCenters = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymCenters collection (array).
	 *
	 * By default this just sets the collRikssymCenters collection to an empty array (like clearcollRikssymCenters());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymCenters()
	{
		$this->collRikssymCenters = array();
	}

	/**
	 * Gets an array of RikssymCenter objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymGeoregion has previously been saved, it will retrieve
	 * related RikssymCenters from storage. If this RikssymGeoregion is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymCenter[]
	 * @throws     PropelException
	 */
	public function getRikssymCenters($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymCenters === null) {
			if ($this->isNew()) {
			   $this->collRikssymCenters = array();
			} else {

				$criteria->add(RikssymCenterPeer::REGION_ID, $this->id);

				RikssymCenterPeer::addSelectColumns($criteria);
				$this->collRikssymCenters = RikssymCenterPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymCenterPeer::REGION_ID, $this->id);

				RikssymCenterPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymCenterCriteria) || !$this->lastRikssymCenterCriteria->equals($criteria)) {
					$this->collRikssymCenters = RikssymCenterPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymCenterCriteria = $criteria;
		return $this->collRikssymCenters;
	}

	/**
	 * Returns the number of related RikssymCenter objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymCenter objects.
	 * @throws     PropelException
	 */
	public function countRikssymCenters(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymCenters === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymCenterPeer::REGION_ID, $this->id);

				$count = RikssymCenterPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymCenterPeer::REGION_ID, $this->id);

				if (!isset($this->lastRikssymCenterCriteria) || !$this->lastRikssymCenterCriteria->equals($criteria)) {
					$count = RikssymCenterPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymCenters);
				}
			} else {
				$count = count($this->collRikssymCenters);
			}
		}
		$this->lastRikssymCenterCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymCenter object to this object
	 * through the RikssymCenter foreign key attribute.
	 *
	 * @param      RikssymCenter $l RikssymCenter
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymCenter(RikssymCenter $l)
	{
		if ($this->collRikssymCenters === null) {
			$this->initRikssymCenters();
		}
		if (!in_array($l, $this->collRikssymCenters, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymCenters, $l);
			$l->setRikssymGeoregion($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collRikssymCountrys) {
				foreach ((array) $this->collRikssymCountrys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymArrangements) {
				foreach ((array) $this->collRikssymArrangements as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymJournals) {
				foreach ((array) $this->collRikssymJournals as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymCenters) {
				foreach ((array) $this->collRikssymCenters as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collRikssymCountrys = null;
		$this->collRikssymArrangements = null;
		$this->collRikssymJournals = null;
		$this->collRikssymCenters = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRikssymGeoregion:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRikssymGeoregion::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRikssymGeoregion
