<?php

/**
 * Base class that represents a row from the 'rikssym_country' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu May 27 16:34:57 2010
 *
 * @package    lib.model.om
 */
abstract class BaseRikssymCountry extends BaseObject  implements Persistent {


  const PEER = 'RikssymCountryPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RikssymCountryPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the show field.
	 * @var        boolean
	 */
	protected $show;

	/**
	 * The value for the iso_countrycode field.
	 * @var        string
	 */
	protected $iso_countrycode;

	/**
	 * The value for the iso3_countrycode field.
	 * @var        string
	 */
	protected $iso3_countrycode;

	/**
	 * The value for the cow_code field.
	 * @var        int
	 */
	protected $cow_code;

	/**
	 * The value for the georegion field.
	 * @var        int
	 */
	protected $georegion;

	/**
	 * @var        RikssymGeoregion
	 */
	protected $aRikssymGeoregion;

	/**
	 * @var        array RikssymMaster[] Collection to store aggregation of RikssymMaster objects.
	 */
	protected $collRikssymMasters;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymMasters.
	 */
	private $lastRikssymMasterCriteria = null;

	/**
	 * @var        array RikssymTraining[] Collection to store aggregation of RikssymTraining objects.
	 */
	protected $collRikssymTrainings;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymTrainings.
	 */
	private $lastRikssymTrainingCriteria = null;

	/**
	 * @var        array RikssymPhd[] Collection to store aggregation of RikssymPhd objects.
	 */
	protected $collRikssymPhds;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymPhds.
	 */
	private $lastRikssymPhdCriteria = null;

	/**
	 * @var        array RikssymArrangementCountry[] Collection to store aggregation of RikssymArrangementCountry objects.
	 */
	protected $collRikssymArrangementCountrys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymArrangementCountrys.
	 */
	private $lastRikssymArrangementCountryCriteria = null;

	/**
	 * @var        array RikssymDocumentEntity[] Collection to store aggregation of RikssymDocumentEntity objects.
	 */
	protected $collRikssymDocumentEntitys;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymDocumentEntitys.
	 */
	private $lastRikssymDocumentEntityCriteria = null;

	/**
	 * @var        array RikssymData[] Collection to store aggregation of RikssymData objects.
	 */
	protected $collRikssymDatasRelatedByReporterId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymDatasRelatedByReporterId.
	 */
	private $lastRikssymDataRelatedByReporterIdCriteria = null;

	/**
	 * @var        array RikssymData[] Collection to store aggregation of RikssymData objects.
	 */
	protected $collRikssymDatasRelatedByPartnerId;

	/**
	 * @var        Criteria The criteria used to select the current contents of collRikssymDatasRelatedByPartnerId.
	 */
	private $lastRikssymDataRelatedByPartnerIdCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRikssymCountry object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [show] column value.
	 * 
	 * @return     boolean
	 */
	public function getShow()
	{
		return $this->show;
	}

	/**
	 * Get the [iso_countrycode] column value.
	 * 
	 * @return     string
	 */
	public function getIsoCountrycode()
	{
		return $this->iso_countrycode;
	}

	/**
	 * Get the [iso3_countrycode] column value.
	 * 
	 * @return     string
	 */
	public function getIso3Countrycode()
	{
		return $this->iso3_countrycode;
	}

	/**
	 * Get the [cow_code] column value.
	 * 
	 * @return     int
	 */
	public function getCowCode()
	{
		return $this->cow_code;
	}

	/**
	 * Get the [georegion] column value.
	 * 
	 * @return     int
	 */
	public function getGeoregion()
	{
		return $this->georegion;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [show] column.
	 * 
	 * @param      boolean $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setShow($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->show !== $v) {
			$this->show = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::SHOW;
		}

		return $this;
	} // setShow()

	/**
	 * Set the value of [iso_countrycode] column.
	 * 
	 * @param      string $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setIsoCountrycode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->iso_countrycode !== $v) {
			$this->iso_countrycode = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::ISO_COUNTRYCODE;
		}

		return $this;
	} // setIsoCountrycode()

	/**
	 * Set the value of [iso3_countrycode] column.
	 * 
	 * @param      string $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setIso3Countrycode($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->iso3_countrycode !== $v) {
			$this->iso3_countrycode = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::ISO3_COUNTRYCODE;
		}

		return $this;
	} // setIso3Countrycode()

	/**
	 * Set the value of [cow_code] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setCowCode($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->cow_code !== $v) {
			$this->cow_code = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::COW_CODE;
		}

		return $this;
	} // setCowCode()

	/**
	 * Set the value of [georegion] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymCountry The current object (for fluent API support)
	 */
	public function setGeoregion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->georegion !== $v) {
			$this->georegion = $v;
			$this->modifiedColumns[] = RikssymCountryPeer::GEOREGION;
		}

		if ($this->aRikssymGeoregion !== null && $this->aRikssymGeoregion->getId() !== $v) {
			$this->aRikssymGeoregion = null;
		}

		return $this;
	} // setGeoregion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->show = ($row[$startcol + 2] !== null) ? (boolean) $row[$startcol + 2] : null;
			$this->iso_countrycode = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->iso3_countrycode = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->cow_code = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->georegion = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = RikssymCountryPeer::NUM_COLUMNS - RikssymCountryPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RikssymCountry object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aRikssymGeoregion !== null && $this->georegion !== $this->aRikssymGeoregion->getId()) {
			$this->aRikssymGeoregion = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymCountryPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RikssymCountryPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aRikssymGeoregion = null;
			$this->collRikssymMasters = null;
			$this->lastRikssymMasterCriteria = null;

			$this->collRikssymTrainings = null;
			$this->lastRikssymTrainingCriteria = null;

			$this->collRikssymPhds = null;
			$this->lastRikssymPhdCriteria = null;

			$this->collRikssymArrangementCountrys = null;
			$this->lastRikssymArrangementCountryCriteria = null;

			$this->collRikssymDocumentEntitys = null;
			$this->lastRikssymDocumentEntityCriteria = null;

			$this->collRikssymDatasRelatedByReporterId = null;
			$this->lastRikssymDataRelatedByReporterIdCriteria = null;

			$this->collRikssymDatasRelatedByPartnerId = null;
			$this->lastRikssymDataRelatedByPartnerIdCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRikssymCountry:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymCountryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RikssymCountryPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRikssymCountry:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRikssymCountry:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymCountryPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRikssymCountry:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RikssymCountryPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRikssymGeoregion !== null) {
				if ($this->aRikssymGeoregion->isModified() || $this->aRikssymGeoregion->isNew()) {
					$affectedRows += $this->aRikssymGeoregion->save($con);
				}
				$this->setRikssymGeoregion($this->aRikssymGeoregion);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RikssymCountryPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RikssymCountryPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RikssymCountryPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collRikssymMasters !== null) {
				foreach ($this->collRikssymMasters as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymTrainings !== null) {
				foreach ($this->collRikssymTrainings as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymPhds !== null) {
				foreach ($this->collRikssymPhds as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymArrangementCountrys !== null) {
				foreach ($this->collRikssymArrangementCountrys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymDocumentEntitys !== null) {
				foreach ($this->collRikssymDocumentEntitys as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymDatasRelatedByReporterId !== null) {
				foreach ($this->collRikssymDatasRelatedByReporterId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collRikssymDatasRelatedByPartnerId !== null) {
				foreach ($this->collRikssymDatasRelatedByPartnerId as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRikssymGeoregion !== null) {
				if (!$this->aRikssymGeoregion->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRikssymGeoregion->getValidationFailures());
				}
			}


			if (($retval = RikssymCountryPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collRikssymMasters !== null) {
					foreach ($this->collRikssymMasters as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymTrainings !== null) {
					foreach ($this->collRikssymTrainings as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymPhds !== null) {
					foreach ($this->collRikssymPhds as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymArrangementCountrys !== null) {
					foreach ($this->collRikssymArrangementCountrys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymDocumentEntitys !== null) {
					foreach ($this->collRikssymDocumentEntitys as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymDatasRelatedByReporterId !== null) {
					foreach ($this->collRikssymDatasRelatedByReporterId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collRikssymDatasRelatedByPartnerId !== null) {
					foreach ($this->collRikssymDatasRelatedByPartnerId as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RikssymCountryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getShow();
				break;
			case 3:
				return $this->getIsoCountrycode();
				break;
			case 4:
				return $this->getIso3Countrycode();
				break;
			case 5:
				return $this->getCowCode();
				break;
			case 6:
				return $this->getGeoregion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RikssymCountryPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getShow(),
			$keys[3] => $this->getIsoCountrycode(),
			$keys[4] => $this->getIso3Countrycode(),
			$keys[5] => $this->getCowCode(),
			$keys[6] => $this->getGeoregion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RikssymCountryPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setShow($value);
				break;
			case 3:
				$this->setIsoCountrycode($value);
				break;
			case 4:
				$this->setIso3Countrycode($value);
				break;
			case 5:
				$this->setCowCode($value);
				break;
			case 6:
				$this->setGeoregion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RikssymCountryPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setShow($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setIsoCountrycode($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setIso3Countrycode($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setCowCode($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setGeoregion($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);

		if ($this->isColumnModified(RikssymCountryPeer::ID)) $criteria->add(RikssymCountryPeer::ID, $this->id);
		if ($this->isColumnModified(RikssymCountryPeer::NAME)) $criteria->add(RikssymCountryPeer::NAME, $this->name);
		if ($this->isColumnModified(RikssymCountryPeer::SHOW)) $criteria->add(RikssymCountryPeer::SHOW, $this->show);
		if ($this->isColumnModified(RikssymCountryPeer::ISO_COUNTRYCODE)) $criteria->add(RikssymCountryPeer::ISO_COUNTRYCODE, $this->iso_countrycode);
		if ($this->isColumnModified(RikssymCountryPeer::ISO3_COUNTRYCODE)) $criteria->add(RikssymCountryPeer::ISO3_COUNTRYCODE, $this->iso3_countrycode);
		if ($this->isColumnModified(RikssymCountryPeer::COW_CODE)) $criteria->add(RikssymCountryPeer::COW_CODE, $this->cow_code);
		if ($this->isColumnModified(RikssymCountryPeer::GEOREGION)) $criteria->add(RikssymCountryPeer::GEOREGION, $this->georegion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);

		$criteria->add(RikssymCountryPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RikssymCountry (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setShow($this->show);

		$copyObj->setIsoCountrycode($this->iso_countrycode);

		$copyObj->setIso3Countrycode($this->iso3_countrycode);

		$copyObj->setCowCode($this->cow_code);

		$copyObj->setGeoregion($this->georegion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getRikssymMasters() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymMaster($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymTrainings() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymTraining($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymPhds() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymPhd($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymArrangementCountrys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymArrangementCountry($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymDocumentEntitys() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymDocumentEntity($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymDatasRelatedByReporterId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymDataRelatedByReporterId($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getRikssymDatasRelatedByPartnerId() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addRikssymDataRelatedByPartnerId($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RikssymCountry Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RikssymCountryPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RikssymCountryPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a RikssymGeoregion object.
	 *
	 * @param      RikssymGeoregion $v
	 * @return     RikssymCountry The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRikssymGeoregion(RikssymGeoregion $v = null)
	{
		if ($v === null) {
			$this->setGeoregion(NULL);
		} else {
			$this->setGeoregion($v->getId());
		}

		$this->aRikssymGeoregion = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RikssymGeoregion object, it will not be re-added.
		if ($v !== null) {
			$v->addRikssymCountry($this);
		}

		return $this;
	}


	/**
	 * Get the associated RikssymGeoregion object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RikssymGeoregion The associated RikssymGeoregion object.
	 * @throws     PropelException
	 */
	public function getRikssymGeoregion(PropelPDO $con = null)
	{
		if ($this->aRikssymGeoregion === null && ($this->georegion !== null)) {
			$c = new Criteria(RikssymGeoregionPeer::DATABASE_NAME);
			$c->add(RikssymGeoregionPeer::ID, $this->georegion);
			$this->aRikssymGeoregion = RikssymGeoregionPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRikssymGeoregion->addRikssymCountrys($this);
			 */
		}
		return $this->aRikssymGeoregion;
	}

	/**
	 * Clears out the collRikssymMasters collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymMasters()
	 */
	public function clearRikssymMasters()
	{
		$this->collRikssymMasters = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymMasters collection (array).
	 *
	 * By default this just sets the collRikssymMasters collection to an empty array (like clearcollRikssymMasters());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymMasters()
	{
		$this->collRikssymMasters = array();
	}

	/**
	 * Gets an array of RikssymMaster objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymMasters from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymMaster[]
	 * @throws     PropelException
	 */
	public function getRikssymMasters($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymMasters === null) {
			if ($this->isNew()) {
			   $this->collRikssymMasters = array();
			} else {

				$criteria->add(RikssymMasterPeer::COUNTRY_ID, $this->id);

				RikssymMasterPeer::addSelectColumns($criteria);
				$this->collRikssymMasters = RikssymMasterPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymMasterPeer::COUNTRY_ID, $this->id);

				RikssymMasterPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymMasterCriteria) || !$this->lastRikssymMasterCriteria->equals($criteria)) {
					$this->collRikssymMasters = RikssymMasterPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymMasterCriteria = $criteria;
		return $this->collRikssymMasters;
	}

	/**
	 * Returns the number of related RikssymMaster objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymMaster objects.
	 * @throws     PropelException
	 */
	public function countRikssymMasters(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymMasters === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymMasterPeer::COUNTRY_ID, $this->id);

				$count = RikssymMasterPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymMasterPeer::COUNTRY_ID, $this->id);

				if (!isset($this->lastRikssymMasterCriteria) || !$this->lastRikssymMasterCriteria->equals($criteria)) {
					$count = RikssymMasterPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymMasters);
				}
			} else {
				$count = count($this->collRikssymMasters);
			}
		}
		$this->lastRikssymMasterCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymMaster object to this object
	 * through the RikssymMaster foreign key attribute.
	 *
	 * @param      RikssymMaster $l RikssymMaster
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymMaster(RikssymMaster $l)
	{
		if ($this->collRikssymMasters === null) {
			$this->initRikssymMasters();
		}
		if (!in_array($l, $this->collRikssymMasters, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymMasters, $l);
			$l->setRikssymCountry($this);
		}
	}

	/**
	 * Clears out the collRikssymTrainings collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymTrainings()
	 */
	public function clearRikssymTrainings()
	{
		$this->collRikssymTrainings = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymTrainings collection (array).
	 *
	 * By default this just sets the collRikssymTrainings collection to an empty array (like clearcollRikssymTrainings());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymTrainings()
	{
		$this->collRikssymTrainings = array();
	}

	/**
	 * Gets an array of RikssymTraining objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymTrainings from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymTraining[]
	 * @throws     PropelException
	 */
	public function getRikssymTrainings($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymTrainings === null) {
			if ($this->isNew()) {
			   $this->collRikssymTrainings = array();
			} else {

				$criteria->add(RikssymTrainingPeer::COUNTRY_ID, $this->id);

				RikssymTrainingPeer::addSelectColumns($criteria);
				$this->collRikssymTrainings = RikssymTrainingPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymTrainingPeer::COUNTRY_ID, $this->id);

				RikssymTrainingPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymTrainingCriteria) || !$this->lastRikssymTrainingCriteria->equals($criteria)) {
					$this->collRikssymTrainings = RikssymTrainingPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymTrainingCriteria = $criteria;
		return $this->collRikssymTrainings;
	}

	/**
	 * Returns the number of related RikssymTraining objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymTraining objects.
	 * @throws     PropelException
	 */
	public function countRikssymTrainings(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymTrainings === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymTrainingPeer::COUNTRY_ID, $this->id);

				$count = RikssymTrainingPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymTrainingPeer::COUNTRY_ID, $this->id);

				if (!isset($this->lastRikssymTrainingCriteria) || !$this->lastRikssymTrainingCriteria->equals($criteria)) {
					$count = RikssymTrainingPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymTrainings);
				}
			} else {
				$count = count($this->collRikssymTrainings);
			}
		}
		$this->lastRikssymTrainingCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymTraining object to this object
	 * through the RikssymTraining foreign key attribute.
	 *
	 * @param      RikssymTraining $l RikssymTraining
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymTraining(RikssymTraining $l)
	{
		if ($this->collRikssymTrainings === null) {
			$this->initRikssymTrainings();
		}
		if (!in_array($l, $this->collRikssymTrainings, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymTrainings, $l);
			$l->setRikssymCountry($this);
		}
	}

	/**
	 * Clears out the collRikssymPhds collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymPhds()
	 */
	public function clearRikssymPhds()
	{
		$this->collRikssymPhds = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymPhds collection (array).
	 *
	 * By default this just sets the collRikssymPhds collection to an empty array (like clearcollRikssymPhds());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymPhds()
	{
		$this->collRikssymPhds = array();
	}

	/**
	 * Gets an array of RikssymPhd objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymPhds from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymPhd[]
	 * @throws     PropelException
	 */
	public function getRikssymPhds($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymPhds === null) {
			if ($this->isNew()) {
			   $this->collRikssymPhds = array();
			} else {

				$criteria->add(RikssymPhdPeer::COUNTRY_ID, $this->id);

				RikssymPhdPeer::addSelectColumns($criteria);
				$this->collRikssymPhds = RikssymPhdPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymPhdPeer::COUNTRY_ID, $this->id);

				RikssymPhdPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymPhdCriteria) || !$this->lastRikssymPhdCriteria->equals($criteria)) {
					$this->collRikssymPhds = RikssymPhdPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymPhdCriteria = $criteria;
		return $this->collRikssymPhds;
	}

	/**
	 * Returns the number of related RikssymPhd objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymPhd objects.
	 * @throws     PropelException
	 */
	public function countRikssymPhds(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymPhds === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymPhdPeer::COUNTRY_ID, $this->id);

				$count = RikssymPhdPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymPhdPeer::COUNTRY_ID, $this->id);

				if (!isset($this->lastRikssymPhdCriteria) || !$this->lastRikssymPhdCriteria->equals($criteria)) {
					$count = RikssymPhdPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymPhds);
				}
			} else {
				$count = count($this->collRikssymPhds);
			}
		}
		$this->lastRikssymPhdCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymPhd object to this object
	 * through the RikssymPhd foreign key attribute.
	 *
	 * @param      RikssymPhd $l RikssymPhd
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymPhd(RikssymPhd $l)
	{
		if ($this->collRikssymPhds === null) {
			$this->initRikssymPhds();
		}
		if (!in_array($l, $this->collRikssymPhds, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymPhds, $l);
			$l->setRikssymCountry($this);
		}
	}

	/**
	 * Clears out the collRikssymArrangementCountrys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymArrangementCountrys()
	 */
	public function clearRikssymArrangementCountrys()
	{
		$this->collRikssymArrangementCountrys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymArrangementCountrys collection (array).
	 *
	 * By default this just sets the collRikssymArrangementCountrys collection to an empty array (like clearcollRikssymArrangementCountrys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymArrangementCountrys()
	{
		$this->collRikssymArrangementCountrys = array();
	}

	/**
	 * Gets an array of RikssymArrangementCountry objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymArrangementCountrys from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymArrangementCountry[]
	 * @throws     PropelException
	 */
	public function getRikssymArrangementCountrys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymArrangementCountrys === null) {
			if ($this->isNew()) {
			   $this->collRikssymArrangementCountrys = array();
			} else {

				$criteria->add(RikssymArrangementCountryPeer::COUNTRY_ID, $this->id);

				RikssymArrangementCountryPeer::addSelectColumns($criteria);
				$this->collRikssymArrangementCountrys = RikssymArrangementCountryPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymArrangementCountryPeer::COUNTRY_ID, $this->id);

				RikssymArrangementCountryPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymArrangementCountryCriteria) || !$this->lastRikssymArrangementCountryCriteria->equals($criteria)) {
					$this->collRikssymArrangementCountrys = RikssymArrangementCountryPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymArrangementCountryCriteria = $criteria;
		return $this->collRikssymArrangementCountrys;
	}

	/**
	 * Returns the number of related RikssymArrangementCountry objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymArrangementCountry objects.
	 * @throws     PropelException
	 */
	public function countRikssymArrangementCountrys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymArrangementCountrys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymArrangementCountryPeer::COUNTRY_ID, $this->id);

				$count = RikssymArrangementCountryPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymArrangementCountryPeer::COUNTRY_ID, $this->id);

				if (!isset($this->lastRikssymArrangementCountryCriteria) || !$this->lastRikssymArrangementCountryCriteria->equals($criteria)) {
					$count = RikssymArrangementCountryPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymArrangementCountrys);
				}
			} else {
				$count = count($this->collRikssymArrangementCountrys);
			}
		}
		$this->lastRikssymArrangementCountryCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymArrangementCountry object to this object
	 * through the RikssymArrangementCountry foreign key attribute.
	 *
	 * @param      RikssymArrangementCountry $l RikssymArrangementCountry
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymArrangementCountry(RikssymArrangementCountry $l)
	{
		if ($this->collRikssymArrangementCountrys === null) {
			$this->initRikssymArrangementCountrys();
		}
		if (!in_array($l, $this->collRikssymArrangementCountrys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymArrangementCountrys, $l);
			$l->setRikssymCountry($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymArrangementCountrys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymArrangementCountrysJoinRikssymArrangement($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymArrangementCountrys === null) {
			if ($this->isNew()) {
				$this->collRikssymArrangementCountrys = array();
			} else {

				$criteria->add(RikssymArrangementCountryPeer::COUNTRY_ID, $this->id);

				$this->collRikssymArrangementCountrys = RikssymArrangementCountryPeer::doSelectJoinRikssymArrangement($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymArrangementCountryPeer::COUNTRY_ID, $this->id);

			if (!isset($this->lastRikssymArrangementCountryCriteria) || !$this->lastRikssymArrangementCountryCriteria->equals($criteria)) {
				$this->collRikssymArrangementCountrys = RikssymArrangementCountryPeer::doSelectJoinRikssymArrangement($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymArrangementCountryCriteria = $criteria;

		return $this->collRikssymArrangementCountrys;
	}

	/**
	 * Clears out the collRikssymDocumentEntitys collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymDocumentEntitys()
	 */
	public function clearRikssymDocumentEntitys()
	{
		$this->collRikssymDocumentEntitys = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymDocumentEntitys collection (array).
	 *
	 * By default this just sets the collRikssymDocumentEntitys collection to an empty array (like clearcollRikssymDocumentEntitys());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymDocumentEntitys()
	{
		$this->collRikssymDocumentEntitys = array();
	}

	/**
	 * Gets an array of RikssymDocumentEntity objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymDocumentEntitys from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymDocumentEntity[]
	 * @throws     PropelException
	 */
	public function getRikssymDocumentEntitys($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDocumentEntitys === null) {
			if ($this->isNew()) {
			   $this->collRikssymDocumentEntitys = array();
			} else {

				$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

				RikssymDocumentEntityPeer::addSelectColumns($criteria);
				$this->collRikssymDocumentEntitys = RikssymDocumentEntityPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

				RikssymDocumentEntityPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymDocumentEntityCriteria) || !$this->lastRikssymDocumentEntityCriteria->equals($criteria)) {
					$this->collRikssymDocumentEntitys = RikssymDocumentEntityPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymDocumentEntityCriteria = $criteria;
		return $this->collRikssymDocumentEntitys;
	}

	/**
	 * Returns the number of related RikssymDocumentEntity objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymDocumentEntity objects.
	 * @throws     PropelException
	 */
	public function countRikssymDocumentEntitys(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymDocumentEntitys === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

				$count = RikssymDocumentEntityPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

				if (!isset($this->lastRikssymDocumentEntityCriteria) || !$this->lastRikssymDocumentEntityCriteria->equals($criteria)) {
					$count = RikssymDocumentEntityPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymDocumentEntitys);
				}
			} else {
				$count = count($this->collRikssymDocumentEntitys);
			}
		}
		$this->lastRikssymDocumentEntityCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymDocumentEntity object to this object
	 * through the RikssymDocumentEntity foreign key attribute.
	 *
	 * @param      RikssymDocumentEntity $l RikssymDocumentEntity
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymDocumentEntity(RikssymDocumentEntity $l)
	{
		if ($this->collRikssymDocumentEntitys === null) {
			$this->initRikssymDocumentEntitys();
		}
		if (!in_array($l, $this->collRikssymDocumentEntitys, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymDocumentEntitys, $l);
			$l->setRikssymCountry($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymDocumentEntitys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymDocumentEntitysJoinRikssymDocument($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDocumentEntitys === null) {
			if ($this->isNew()) {
				$this->collRikssymDocumentEntitys = array();
			} else {

				$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

				$this->collRikssymDocumentEntitys = RikssymDocumentEntityPeer::doSelectJoinRikssymDocument($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

			if (!isset($this->lastRikssymDocumentEntityCriteria) || !$this->lastRikssymDocumentEntityCriteria->equals($criteria)) {
				$this->collRikssymDocumentEntitys = RikssymDocumentEntityPeer::doSelectJoinRikssymDocument($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymDocumentEntityCriteria = $criteria;

		return $this->collRikssymDocumentEntitys;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymDocumentEntitys from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymDocumentEntitysJoinRikssymArrangement($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDocumentEntitys === null) {
			if ($this->isNew()) {
				$this->collRikssymDocumentEntitys = array();
			} else {

				$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

				$this->collRikssymDocumentEntitys = RikssymDocumentEntityPeer::doSelectJoinRikssymArrangement($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymDocumentEntityPeer::COUNTRY_ID, $this->id);

			if (!isset($this->lastRikssymDocumentEntityCriteria) || !$this->lastRikssymDocumentEntityCriteria->equals($criteria)) {
				$this->collRikssymDocumentEntitys = RikssymDocumentEntityPeer::doSelectJoinRikssymArrangement($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymDocumentEntityCriteria = $criteria;

		return $this->collRikssymDocumentEntitys;
	}

	/**
	 * Clears out the collRikssymDatasRelatedByReporterId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymDatasRelatedByReporterId()
	 */
	public function clearRikssymDatasRelatedByReporterId()
	{
		$this->collRikssymDatasRelatedByReporterId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymDatasRelatedByReporterId collection (array).
	 *
	 * By default this just sets the collRikssymDatasRelatedByReporterId collection to an empty array (like clearcollRikssymDatasRelatedByReporterId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymDatasRelatedByReporterId()
	{
		$this->collRikssymDatasRelatedByReporterId = array();
	}

	/**
	 * Gets an array of RikssymData objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymDatasRelatedByReporterId from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymData[]
	 * @throws     PropelException
	 */
	public function getRikssymDatasRelatedByReporterId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDatasRelatedByReporterId === null) {
			if ($this->isNew()) {
			   $this->collRikssymDatasRelatedByReporterId = array();
			} else {

				$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

				RikssymDataPeer::addSelectColumns($criteria);
				$this->collRikssymDatasRelatedByReporterId = RikssymDataPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

				RikssymDataPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymDataRelatedByReporterIdCriteria) || !$this->lastRikssymDataRelatedByReporterIdCriteria->equals($criteria)) {
					$this->collRikssymDatasRelatedByReporterId = RikssymDataPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymDataRelatedByReporterIdCriteria = $criteria;
		return $this->collRikssymDatasRelatedByReporterId;
	}

	/**
	 * Returns the number of related RikssymData objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymData objects.
	 * @throws     PropelException
	 */
	public function countRikssymDatasRelatedByReporterId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymDatasRelatedByReporterId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

				$count = RikssymDataPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

				if (!isset($this->lastRikssymDataRelatedByReporterIdCriteria) || !$this->lastRikssymDataRelatedByReporterIdCriteria->equals($criteria)) {
					$count = RikssymDataPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymDatasRelatedByReporterId);
				}
			} else {
				$count = count($this->collRikssymDatasRelatedByReporterId);
			}
		}
		$this->lastRikssymDataRelatedByReporterIdCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymData object to this object
	 * through the RikssymData foreign key attribute.
	 *
	 * @param      RikssymData $l RikssymData
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymDataRelatedByReporterId(RikssymData $l)
	{
		if ($this->collRikssymDatasRelatedByReporterId === null) {
			$this->initRikssymDatasRelatedByReporterId();
		}
		if (!in_array($l, $this->collRikssymDatasRelatedByReporterId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymDatasRelatedByReporterId, $l);
			$l->setRikssymCountryRelatedByReporterId($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymDatasRelatedByReporterId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymDatasRelatedByReporterIdJoinRikssymDatatype($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDatasRelatedByReporterId === null) {
			if ($this->isNew()) {
				$this->collRikssymDatasRelatedByReporterId = array();
			} else {

				$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

				$this->collRikssymDatasRelatedByReporterId = RikssymDataPeer::doSelectJoinRikssymDatatype($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

			if (!isset($this->lastRikssymDataRelatedByReporterIdCriteria) || !$this->lastRikssymDataRelatedByReporterIdCriteria->equals($criteria)) {
				$this->collRikssymDatasRelatedByReporterId = RikssymDataPeer::doSelectJoinRikssymDatatype($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymDataRelatedByReporterIdCriteria = $criteria;

		return $this->collRikssymDatasRelatedByReporterId;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymDatasRelatedByReporterId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymDatasRelatedByReporterIdJoinRikssymSources($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDatasRelatedByReporterId === null) {
			if ($this->isNew()) {
				$this->collRikssymDatasRelatedByReporterId = array();
			} else {

				$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

				$this->collRikssymDatasRelatedByReporterId = RikssymDataPeer::doSelectJoinRikssymSources($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymDataPeer::REPORTER_ID, $this->id);

			if (!isset($this->lastRikssymDataRelatedByReporterIdCriteria) || !$this->lastRikssymDataRelatedByReporterIdCriteria->equals($criteria)) {
				$this->collRikssymDatasRelatedByReporterId = RikssymDataPeer::doSelectJoinRikssymSources($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymDataRelatedByReporterIdCriteria = $criteria;

		return $this->collRikssymDatasRelatedByReporterId;
	}

	/**
	 * Clears out the collRikssymDatasRelatedByPartnerId collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addRikssymDatasRelatedByPartnerId()
	 */
	public function clearRikssymDatasRelatedByPartnerId()
	{
		$this->collRikssymDatasRelatedByPartnerId = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collRikssymDatasRelatedByPartnerId collection (array).
	 *
	 * By default this just sets the collRikssymDatasRelatedByPartnerId collection to an empty array (like clearcollRikssymDatasRelatedByPartnerId());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initRikssymDatasRelatedByPartnerId()
	{
		$this->collRikssymDatasRelatedByPartnerId = array();
	}

	/**
	 * Gets an array of RikssymData objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this RikssymCountry has previously been saved, it will retrieve
	 * related RikssymDatasRelatedByPartnerId from storage. If this RikssymCountry is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array RikssymData[]
	 * @throws     PropelException
	 */
	public function getRikssymDatasRelatedByPartnerId($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDatasRelatedByPartnerId === null) {
			if ($this->isNew()) {
			   $this->collRikssymDatasRelatedByPartnerId = array();
			} else {

				$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

				RikssymDataPeer::addSelectColumns($criteria);
				$this->collRikssymDatasRelatedByPartnerId = RikssymDataPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

				RikssymDataPeer::addSelectColumns($criteria);
				if (!isset($this->lastRikssymDataRelatedByPartnerIdCriteria) || !$this->lastRikssymDataRelatedByPartnerIdCriteria->equals($criteria)) {
					$this->collRikssymDatasRelatedByPartnerId = RikssymDataPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastRikssymDataRelatedByPartnerIdCriteria = $criteria;
		return $this->collRikssymDatasRelatedByPartnerId;
	}

	/**
	 * Returns the number of related RikssymData objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related RikssymData objects.
	 * @throws     PropelException
	 */
	public function countRikssymDatasRelatedByPartnerId(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collRikssymDatasRelatedByPartnerId === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

				$count = RikssymDataPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

				if (!isset($this->lastRikssymDataRelatedByPartnerIdCriteria) || !$this->lastRikssymDataRelatedByPartnerIdCriteria->equals($criteria)) {
					$count = RikssymDataPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collRikssymDatasRelatedByPartnerId);
				}
			} else {
				$count = count($this->collRikssymDatasRelatedByPartnerId);
			}
		}
		$this->lastRikssymDataRelatedByPartnerIdCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a RikssymData object to this object
	 * through the RikssymData foreign key attribute.
	 *
	 * @param      RikssymData $l RikssymData
	 * @return     void
	 * @throws     PropelException
	 */
	public function addRikssymDataRelatedByPartnerId(RikssymData $l)
	{
		if ($this->collRikssymDatasRelatedByPartnerId === null) {
			$this->initRikssymDatasRelatedByPartnerId();
		}
		if (!in_array($l, $this->collRikssymDatasRelatedByPartnerId, true)) { // only add it if the **same** object is not already associated
			array_push($this->collRikssymDatasRelatedByPartnerId, $l);
			$l->setRikssymCountryRelatedByPartnerId($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymDatasRelatedByPartnerId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymDatasRelatedByPartnerIdJoinRikssymDatatype($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDatasRelatedByPartnerId === null) {
			if ($this->isNew()) {
				$this->collRikssymDatasRelatedByPartnerId = array();
			} else {

				$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

				$this->collRikssymDatasRelatedByPartnerId = RikssymDataPeer::doSelectJoinRikssymDatatype($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

			if (!isset($this->lastRikssymDataRelatedByPartnerIdCriteria) || !$this->lastRikssymDataRelatedByPartnerIdCriteria->equals($criteria)) {
				$this->collRikssymDatasRelatedByPartnerId = RikssymDataPeer::doSelectJoinRikssymDatatype($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymDataRelatedByPartnerIdCriteria = $criteria;

		return $this->collRikssymDatasRelatedByPartnerId;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this RikssymCountry is new, it will return
	 * an empty collection; or if this RikssymCountry has previously
	 * been saved, it will retrieve related RikssymDatasRelatedByPartnerId from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in RikssymCountry.
	 */
	public function getRikssymDatasRelatedByPartnerIdJoinRikssymSources($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(RikssymCountryPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collRikssymDatasRelatedByPartnerId === null) {
			if ($this->isNew()) {
				$this->collRikssymDatasRelatedByPartnerId = array();
			} else {

				$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

				$this->collRikssymDatasRelatedByPartnerId = RikssymDataPeer::doSelectJoinRikssymSources($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(RikssymDataPeer::PARTNER_ID, $this->id);

			if (!isset($this->lastRikssymDataRelatedByPartnerIdCriteria) || !$this->lastRikssymDataRelatedByPartnerIdCriteria->equals($criteria)) {
				$this->collRikssymDatasRelatedByPartnerId = RikssymDataPeer::doSelectJoinRikssymSources($criteria, $con, $join_behavior);
			}
		}
		$this->lastRikssymDataRelatedByPartnerIdCriteria = $criteria;

		return $this->collRikssymDatasRelatedByPartnerId;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collRikssymMasters) {
				foreach ((array) $this->collRikssymMasters as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymTrainings) {
				foreach ((array) $this->collRikssymTrainings as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymPhds) {
				foreach ((array) $this->collRikssymPhds as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymArrangementCountrys) {
				foreach ((array) $this->collRikssymArrangementCountrys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymDocumentEntitys) {
				foreach ((array) $this->collRikssymDocumentEntitys as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymDatasRelatedByReporterId) {
				foreach ((array) $this->collRikssymDatasRelatedByReporterId as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collRikssymDatasRelatedByPartnerId) {
				foreach ((array) $this->collRikssymDatasRelatedByPartnerId as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collRikssymMasters = null;
		$this->collRikssymTrainings = null;
		$this->collRikssymPhds = null;
		$this->collRikssymArrangementCountrys = null;
		$this->collRikssymDocumentEntitys = null;
		$this->collRikssymDatasRelatedByReporterId = null;
		$this->collRikssymDatasRelatedByPartnerId = null;
			$this->aRikssymGeoregion = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRikssymCountry:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRikssymCountry::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRikssymCountry
