<?php

/**
 * Base class that represents a row from the 'rikssym_data' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu May 27 16:34:58 2010
 *
 * @package    lib.model.om
 */
abstract class BaseRikssymData extends BaseObject  implements Persistent {


  const PEER = 'RikssymDataPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RikssymDataPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the reporter_id field.
	 * @var        int
	 */
	protected $reporter_id;

	/**
	 * The value for the partner_id field.
	 * @var        int
	 */
	protected $partner_id;

	/**
	 * The value for the type_id field.
	 * @var        int
	 */
	protected $type_id;

	/**
	 * The value for the value field.
	 * @var        string
	 */
	protected $value;

	/**
	 * The value for the source_id field.
	 * @var        int
	 */
	protected $source_id;

	/**
	 * The value for the period field.
	 * @var        int
	 */
	protected $period;

	/**
	 * @var        RikssymCountry
	 */
	protected $aRikssymCountryRelatedByReporterId;

	/**
	 * @var        RikssymCountry
	 */
	protected $aRikssymCountryRelatedByPartnerId;

	/**
	 * @var        RikssymDatatype
	 */
	protected $aRikssymDatatype;

	/**
	 * @var        RikssymSources
	 */
	protected $aRikssymSources;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRikssymData object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [reporter_id] column value.
	 * 
	 * @return     int
	 */
	public function getReporterId()
	{
		return $this->reporter_id;
	}

	/**
	 * Get the [partner_id] column value.
	 * 
	 * @return     int
	 */
	public function getPartnerId()
	{
		return $this->partner_id;
	}

	/**
	 * Get the [type_id] column value.
	 * 
	 * @return     int
	 */
	public function getTypeId()
	{
		return $this->type_id;
	}

	/**
	 * Get the [value] column value.
	 * 
	 * @return     string
	 */
	public function getValue()
	{
		return $this->value;
	}

	/**
	 * Get the [source_id] column value.
	 * 
	 * @return     int
	 */
	public function getSourceId()
	{
		return $this->source_id;
	}

	/**
	 * Get the [period] column value.
	 * 
	 * @return     int
	 */
	public function getPeriod()
	{
		return $this->period;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RikssymDataPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [reporter_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setReporterId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->reporter_id !== $v) {
			$this->reporter_id = $v;
			$this->modifiedColumns[] = RikssymDataPeer::REPORTER_ID;
		}

		if ($this->aRikssymCountryRelatedByReporterId !== null && $this->aRikssymCountryRelatedByReporterId->getId() !== $v) {
			$this->aRikssymCountryRelatedByReporterId = null;
		}

		return $this;
	} // setReporterId()

	/**
	 * Set the value of [partner_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setPartnerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->partner_id !== $v) {
			$this->partner_id = $v;
			$this->modifiedColumns[] = RikssymDataPeer::PARTNER_ID;
		}

		if ($this->aRikssymCountryRelatedByPartnerId !== null && $this->aRikssymCountryRelatedByPartnerId->getId() !== $v) {
			$this->aRikssymCountryRelatedByPartnerId = null;
		}

		return $this;
	} // setPartnerId()

	/**
	 * Set the value of [type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->type_id !== $v) {
			$this->type_id = $v;
			$this->modifiedColumns[] = RikssymDataPeer::TYPE_ID;
		}

		if ($this->aRikssymDatatype !== null && $this->aRikssymDatatype->getId() !== $v) {
			$this->aRikssymDatatype = null;
		}

		return $this;
	} // setTypeId()

	/**
	 * Set the value of [value] column.
	 * 
	 * @param      string $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setValue($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->value !== $v) {
			$this->value = $v;
			$this->modifiedColumns[] = RikssymDataPeer::VALUE;
		}

		return $this;
	} // setValue()

	/**
	 * Set the value of [source_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setSourceId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->source_id !== $v) {
			$this->source_id = $v;
			$this->modifiedColumns[] = RikssymDataPeer::SOURCE_ID;
		}

		if ($this->aRikssymSources !== null && $this->aRikssymSources->getId() !== $v) {
			$this->aRikssymSources = null;
		}

		return $this;
	} // setSourceId()

	/**
	 * Set the value of [period] column.
	 * 
	 * @param      int $v new value
	 * @return     RikssymData The current object (for fluent API support)
	 */
	public function setPeriod($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->period !== $v) {
			$this->period = $v;
			$this->modifiedColumns[] = RikssymDataPeer::PERIOD;
		}

		return $this;
	} // setPeriod()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->reporter_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->partner_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->type_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->value = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->source_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->period = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 7; // 7 = RikssymDataPeer::NUM_COLUMNS - RikssymDataPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RikssymData object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aRikssymCountryRelatedByReporterId !== null && $this->reporter_id !== $this->aRikssymCountryRelatedByReporterId->getId()) {
			$this->aRikssymCountryRelatedByReporterId = null;
		}
		if ($this->aRikssymCountryRelatedByPartnerId !== null && $this->partner_id !== $this->aRikssymCountryRelatedByPartnerId->getId()) {
			$this->aRikssymCountryRelatedByPartnerId = null;
		}
		if ($this->aRikssymDatatype !== null && $this->type_id !== $this->aRikssymDatatype->getId()) {
			$this->aRikssymDatatype = null;
		}
		if ($this->aRikssymSources !== null && $this->source_id !== $this->aRikssymSources->getId()) {
			$this->aRikssymSources = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymDataPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RikssymDataPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aRikssymCountryRelatedByReporterId = null;
			$this->aRikssymCountryRelatedByPartnerId = null;
			$this->aRikssymDatatype = null;
			$this->aRikssymSources = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRikssymData:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymDataPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RikssymDataPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRikssymData:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRikssymData:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RikssymDataPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRikssymData:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RikssymDataPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRikssymCountryRelatedByReporterId !== null) {
				if ($this->aRikssymCountryRelatedByReporterId->isModified() || $this->aRikssymCountryRelatedByReporterId->isNew()) {
					$affectedRows += $this->aRikssymCountryRelatedByReporterId->save($con);
				}
				$this->setRikssymCountryRelatedByReporterId($this->aRikssymCountryRelatedByReporterId);
			}

			if ($this->aRikssymCountryRelatedByPartnerId !== null) {
				if ($this->aRikssymCountryRelatedByPartnerId->isModified() || $this->aRikssymCountryRelatedByPartnerId->isNew()) {
					$affectedRows += $this->aRikssymCountryRelatedByPartnerId->save($con);
				}
				$this->setRikssymCountryRelatedByPartnerId($this->aRikssymCountryRelatedByPartnerId);
			}

			if ($this->aRikssymDatatype !== null) {
				if ($this->aRikssymDatatype->isModified() || $this->aRikssymDatatype->isNew()) {
					$affectedRows += $this->aRikssymDatatype->save($con);
				}
				$this->setRikssymDatatype($this->aRikssymDatatype);
			}

			if ($this->aRikssymSources !== null) {
				if ($this->aRikssymSources->isModified() || $this->aRikssymSources->isNew()) {
					$affectedRows += $this->aRikssymSources->save($con);
				}
				$this->setRikssymSources($this->aRikssymSources);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RikssymDataPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RikssymDataPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RikssymDataPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aRikssymCountryRelatedByReporterId !== null) {
				if (!$this->aRikssymCountryRelatedByReporterId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRikssymCountryRelatedByReporterId->getValidationFailures());
				}
			}

			if ($this->aRikssymCountryRelatedByPartnerId !== null) {
				if (!$this->aRikssymCountryRelatedByPartnerId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRikssymCountryRelatedByPartnerId->getValidationFailures());
				}
			}

			if ($this->aRikssymDatatype !== null) {
				if (!$this->aRikssymDatatype->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRikssymDatatype->getValidationFailures());
				}
			}

			if ($this->aRikssymSources !== null) {
				if (!$this->aRikssymSources->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aRikssymSources->getValidationFailures());
				}
			}


			if (($retval = RikssymDataPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RikssymDataPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getReporterId();
				break;
			case 2:
				return $this->getPartnerId();
				break;
			case 3:
				return $this->getTypeId();
				break;
			case 4:
				return $this->getValue();
				break;
			case 5:
				return $this->getSourceId();
				break;
			case 6:
				return $this->getPeriod();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RikssymDataPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getReporterId(),
			$keys[2] => $this->getPartnerId(),
			$keys[3] => $this->getTypeId(),
			$keys[4] => $this->getValue(),
			$keys[5] => $this->getSourceId(),
			$keys[6] => $this->getPeriod(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RikssymDataPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setReporterId($value);
				break;
			case 2:
				$this->setPartnerId($value);
				break;
			case 3:
				$this->setTypeId($value);
				break;
			case 4:
				$this->setValue($value);
				break;
			case 5:
				$this->setSourceId($value);
				break;
			case 6:
				$this->setPeriod($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RikssymDataPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setReporterId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPartnerId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setTypeId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setValue($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setSourceId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setPeriod($arr[$keys[6]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RikssymDataPeer::DATABASE_NAME);

		if ($this->isColumnModified(RikssymDataPeer::ID)) $criteria->add(RikssymDataPeer::ID, $this->id);
		if ($this->isColumnModified(RikssymDataPeer::REPORTER_ID)) $criteria->add(RikssymDataPeer::REPORTER_ID, $this->reporter_id);
		if ($this->isColumnModified(RikssymDataPeer::PARTNER_ID)) $criteria->add(RikssymDataPeer::PARTNER_ID, $this->partner_id);
		if ($this->isColumnModified(RikssymDataPeer::TYPE_ID)) $criteria->add(RikssymDataPeer::TYPE_ID, $this->type_id);
		if ($this->isColumnModified(RikssymDataPeer::VALUE)) $criteria->add(RikssymDataPeer::VALUE, $this->value);
		if ($this->isColumnModified(RikssymDataPeer::SOURCE_ID)) $criteria->add(RikssymDataPeer::SOURCE_ID, $this->source_id);
		if ($this->isColumnModified(RikssymDataPeer::PERIOD)) $criteria->add(RikssymDataPeer::PERIOD, $this->period);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RikssymDataPeer::DATABASE_NAME);

		$criteria->add(RikssymDataPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RikssymData (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setReporterId($this->reporter_id);

		$copyObj->setPartnerId($this->partner_id);

		$copyObj->setTypeId($this->type_id);

		$copyObj->setValue($this->value);

		$copyObj->setSourceId($this->source_id);

		$copyObj->setPeriod($this->period);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RikssymData Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RikssymDataPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RikssymDataPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a RikssymCountry object.
	 *
	 * @param      RikssymCountry $v
	 * @return     RikssymData The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRikssymCountryRelatedByReporterId(RikssymCountry $v = null)
	{
		if ($v === null) {
			$this->setReporterId(NULL);
		} else {
			$this->setReporterId($v->getId());
		}

		$this->aRikssymCountryRelatedByReporterId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RikssymCountry object, it will not be re-added.
		if ($v !== null) {
			$v->addRikssymDataRelatedByReporterId($this);
		}

		return $this;
	}


	/**
	 * Get the associated RikssymCountry object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RikssymCountry The associated RikssymCountry object.
	 * @throws     PropelException
	 */
	public function getRikssymCountryRelatedByReporterId(PropelPDO $con = null)
	{
		if ($this->aRikssymCountryRelatedByReporterId === null && ($this->reporter_id !== null)) {
			$c = new Criteria(RikssymCountryPeer::DATABASE_NAME);
			$c->add(RikssymCountryPeer::ID, $this->reporter_id);
			$this->aRikssymCountryRelatedByReporterId = RikssymCountryPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRikssymCountryRelatedByReporterId->addRikssymDatasRelatedByReporterId($this);
			 */
		}
		return $this->aRikssymCountryRelatedByReporterId;
	}

	/**
	 * Declares an association between this object and a RikssymCountry object.
	 *
	 * @param      RikssymCountry $v
	 * @return     RikssymData The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRikssymCountryRelatedByPartnerId(RikssymCountry $v = null)
	{
		if ($v === null) {
			$this->setPartnerId(NULL);
		} else {
			$this->setPartnerId($v->getId());
		}

		$this->aRikssymCountryRelatedByPartnerId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RikssymCountry object, it will not be re-added.
		if ($v !== null) {
			$v->addRikssymDataRelatedByPartnerId($this);
		}

		return $this;
	}


	/**
	 * Get the associated RikssymCountry object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RikssymCountry The associated RikssymCountry object.
	 * @throws     PropelException
	 */
	public function getRikssymCountryRelatedByPartnerId(PropelPDO $con = null)
	{
		if ($this->aRikssymCountryRelatedByPartnerId === null && ($this->partner_id !== null)) {
			$c = new Criteria(RikssymCountryPeer::DATABASE_NAME);
			$c->add(RikssymCountryPeer::ID, $this->partner_id);
			$this->aRikssymCountryRelatedByPartnerId = RikssymCountryPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRikssymCountryRelatedByPartnerId->addRikssymDatasRelatedByPartnerId($this);
			 */
		}
		return $this->aRikssymCountryRelatedByPartnerId;
	}

	/**
	 * Declares an association between this object and a RikssymDatatype object.
	 *
	 * @param      RikssymDatatype $v
	 * @return     RikssymData The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRikssymDatatype(RikssymDatatype $v = null)
	{
		if ($v === null) {
			$this->setTypeId(NULL);
		} else {
			$this->setTypeId($v->getId());
		}

		$this->aRikssymDatatype = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RikssymDatatype object, it will not be re-added.
		if ($v !== null) {
			$v->addRikssymData($this);
		}

		return $this;
	}


	/**
	 * Get the associated RikssymDatatype object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RikssymDatatype The associated RikssymDatatype object.
	 * @throws     PropelException
	 */
	public function getRikssymDatatype(PropelPDO $con = null)
	{
		if ($this->aRikssymDatatype === null && ($this->type_id !== null)) {
			$c = new Criteria(RikssymDatatypePeer::DATABASE_NAME);
			$c->add(RikssymDatatypePeer::ID, $this->type_id);
			$this->aRikssymDatatype = RikssymDatatypePeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRikssymDatatype->addRikssymDatas($this);
			 */
		}
		return $this->aRikssymDatatype;
	}

	/**
	 * Declares an association between this object and a RikssymSources object.
	 *
	 * @param      RikssymSources $v
	 * @return     RikssymData The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setRikssymSources(RikssymSources $v = null)
	{
		if ($v === null) {
			$this->setSourceId(NULL);
		} else {
			$this->setSourceId($v->getId());
		}

		$this->aRikssymSources = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the RikssymSources object, it will not be re-added.
		if ($v !== null) {
			$v->addRikssymData($this);
		}

		return $this;
	}


	/**
	 * Get the associated RikssymSources object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     RikssymSources The associated RikssymSources object.
	 * @throws     PropelException
	 */
	public function getRikssymSources(PropelPDO $con = null)
	{
		if ($this->aRikssymSources === null && ($this->source_id !== null)) {
			$c = new Criteria(RikssymSourcesPeer::DATABASE_NAME);
			$c->add(RikssymSourcesPeer::ID, $this->source_id);
			$this->aRikssymSources = RikssymSourcesPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aRikssymSources->addRikssymDatas($this);
			 */
		}
		return $this->aRikssymSources;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aRikssymCountryRelatedByReporterId = null;
			$this->aRikssymCountryRelatedByPartnerId = null;
			$this->aRikssymDatatype = null;
			$this->aRikssymSources = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRikssymData:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRikssymData::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRikssymData
